services:
  - type: web
    name: paroisse-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: paroisse-db
          property: connectionString

databases:
  - name: paroisse-db
    databaseName: paroisses_db
    user: paroisses_user
